- name: split module
  hosts: all
  vars:
    tomcat_url:
    tomcat_url_split:
    tomcat_dir:
  tasks:
    - name: split url
      debug:
        msg: "{{tomcat_url_split}}"

    - name: print tomcat dir
      debug:
        msg: "{{tomcat_dir}}"