- name: split module
  hosts: all
  vars:
    tomcat_url: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.84/bin/apache-tomcat-9.0.84.tar.gz
    tomcat_url_split: "{{tomcat_url.split('/') | last}}"
    tomcat_dir: "{{tomcat_url_split | regex_replace('.tar.gz' ,'')}}"
  tasks:
    - name: split url
      debug:
        msg: "{{tomcat_url_split}}"

    - name: print tomcat dir
      debug:
        msg: "{{tomcat_dir}}"
