- name: Add Grafana APT repository key
  apt_key:
    url: https://packages.grafana.com/gpg.key
    state: present

- name: Add Grafana APT repository
  apt_repository:
    repo: deb https://packages.grafana.com/oss/deb stable main
    state: present
    update_cache: yes

- name: Install Grafana
  apt:
    name: grafana
    state: present

- name: Copy Grafana configuration file
  template:
    src: grafana.ini
    dest: /etc/grafana/grafana.ini
  notify: restart grafana

- name: Start Grafana service
  service:
    name: grafana-server
    state: started
    enabled: true

- name: Wait for Grafana to start
  uri:
    url: http://localhost:3000 ##speecify hostname or ip for grafana server
    timeout: 5
  register: grafana_ready
  until: grafana_ready.status == 200
  retries: 10
  delay: 5
  ignore_errors: yes
