- name: install nginx
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: copy index file
  copy:
    src: index.html
    dest: /var/www/html/index.html
- name: start nginx
  service:
    state: started
    name: nginx