groups:
- name: example
  rules:
  - alert: HighCpuUsage
    expr: node_cpu_seconds_total{mode="idle"} < 0.5
    for: 1m
    labels:
      severity: warning
    annotations:
      description: 'CPU usage is high on instance {{$labels.instance}} (value: {{ $value }})'
      summary: 'High CPU usage on {{$labels.instance}}'
