global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['localhost:9100'] ##specifies the target to scrape, which is the Node Exporter running on localhost and exposing metrics on port 9100
  # Add additional scrape jobs as needed

rule_files:
  - alert.rules.yml
