tomcat_url: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.84/bin/apache-tomcat-9.0.84.tar.gz
tomcat_url_split: "{{tomcat_url.split('/') | last}}"
tomcat_dir: "/opt/{{tomcat_url_split | regex_replace('.tar.gz', '')}}"

USERNAME: dummy
DB_ENDPOINT: dummy
PASSWORD: dummy
DATABASE: dummy
